CESA/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

from api.views import PostViewSet

router = routers.DefaultRouter()
router.register(r'posts', PostViewSet)

from CESA import views, settings
from blog import views as blogViews
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homePage),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('journal/', blogViews.magsPage, name='journals'),
    path('rings/', include('rings.urls'), name='rings'),
    path('about-us/', blogViews.aboutUs, name='about'),
    path('api/', include(router.urls))


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls.static import static
from django.urls import path

from accounts import views
app_name = 'accounts'
urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Account(models.Model):
    authUser = models.OneToOneField(User, on_delete=models.CASCADE)
    studentID = models.IntegerField(unique=True)
    profileImage = models.ImageField(upload_to='media/accounts/profile-photo', null=True)
    accessLevel = models.CharField(max_length=50, choices=[
        ('admin', 'admin'),
        ('author', 'author'),
        ('regular', 'regular')
    ])
    identity = models.CharField(max_length=50, choices=[('student', 'student'),('other', 'other')], null=True)

    def __str__(self):
        return str(self.authUser.username)

accounts/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from CESA.views import homePage


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse(homePage))
            else:
                return HttpResponse("user isn't active")
        else:
            return HttpResponse("invalid user")
    else:
        return render(request, 'accounts/login.html', {})


@login_required(login_url='/accounts/login')
def user_logout(request):

    logout(request)
    return render(request, 'accounts/logout.html',{})

accounts/templates/accounts/account-dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username...">
    <input type="password" name="password" placeholder="password...">
    <input type="submit" value="login">
</form>
</body>
</html>

accounts/templates/accounts/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>logout</title>
</head>
<body>
<h1> you've successfully logged out </h1>
</body>
</html>

accounts/templates/accounts/ring-profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>