CESA/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

from api.views import PostViewSet

router = routers.DefaultRouter()
router.register(r'posts', PostViewSet)

from CESA import views, settings
from blog import views as blogViews
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homePage),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('journal/', blogViews.magsPage, name='journals'),
    path('rings/', include('rings.urls'), name='rings'),
    path('about-us/', blogViews.aboutUs, name='about'),
    path('api/', include(router.urls))


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blog import views
from CESA import  settings

app_name = 'blog'

urlpatterns = [
    path('', views.postsRender , name='blog'),
    path('events', views.postsRender, name="events"),
    path('newpost/', views.newPost, name='submit-post'),
    path('posts/add/', views.addNewPost, name='new-post'),
    path('admin-dashboard/', views.blogAdmin, name='blog-admin'),
    path('categories/<cat_slug>/', views.mainPage, name="posts-by-category-notIndexed"),
    path('page-<int:index>/', views.postsRender, name="home"),
    path('posts/<url_slug>/', views.showPost, name="post-view"),
    path('page-<int:index>/category=<cat_slug>', views.postsByCategory, name='posts-by-category'),
]

rings/urls.py
from django.urls import path
from rings import views
app_name = 'rings'
urlpatterns = [
    path('', views.ringProfiles, name='ring-profiles'),
    path('profiles', views.ringProfiles, name='mainPage')

]

blog/models.py
import os
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
from django.utils import timezone

from CESA import settings
from accounts.models import Account as Author


class Category(models.Model):
    title = models.CharField(primary_key=True, max_length=50, unique=True)
    slug = models.SlugField(unique=True, max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        pass

    class Meta:
        ordering = ['title']


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    language = models.CharField(max_length=2, choices=[('fa', 'FA'), ('en', 'EN')], default='fa')
    type = models.CharField(max_length=10,
                            choices=[('article', 'article'), ('event', 'event'), ], default='article', )
    featured = models.BooleanField(default=False)
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=500, unique=True)
    category = models.ManyToManyField(Category, related_name='category', db_index=True, blank=True)
    submitDate = models.DateTimeField(default=timezone.now)
    publishDate = models.DateTimeField(blank=True, null=True)
    previewImage = models.ImageField(blank=True, upload_to='post-images')
    previewText = models.TextField(max_length=300)
    text = models.TextField(null=True)
    tags = TaggableManager()
    approved = models.BooleanField(default=False)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-view', kwargs={'url_slug': self.slug})

    class Meta:
        ordering = ['-publishDate']


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, )
    name = models.CharField(max_length=50, blank=False)
    email = models.EmailField(max_length=200, null=True)
    text = models.TextField()
    reply = models.TextField(blank=True, null=True)
    submitDate = models.DateTimeField(default=timezone.now)
    publishDate = models.DateTimeField(blank=True, null=True)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return self.email


def fileHandler(instance, filename):
    ext = filename.split('.')[1]
    filename = "%s-No-%d.%s" % (instance.releaseDate, instance.number, ext)
    print(filename)
    print(os.path.join(settings.MEDIA_ROOT, filename))
    return os.path.join(settings.MEDIA_ROOT, filename)

class Journal(models.Model):
    releaseDate = models.DateField(auto_now=True)
    description = models.TextField(blank=True)
    number = models.PositiveIntegerField(unique=True)
    type = models.CharField(max_length=50, choices=[('regular', 'regular'), ('special', 'special')], default='regular')
    electronicFile = models.FileField(upload_to=fileHandler)
    coverImage = models.ImageField(upload_to="journals/journal-covers/")

    def __str__(self):
        return "No. #" + str(self.number)

blog/forms.py
from django import forms

from blog.models import Post


class NewPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = "__all__"
        exclude = ['publishDate', 'approved', 'author', 'submitDate']
        widgets= {
            'previewImage': forms.FileInput(attrs={
                'accept': 'image/*',
            }),
        }

blog/views.py
import math
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from blog.forms import NewPostForm
from accounts.models import Account
from django.contrib.auth import authenticate

from blog.models import Post, Category, Journal


def getAuthStaffUser(request):
    user = None
    if request.user.is_authenticated and not request.user.is_staff:
        username = request.user.username
        user = Account.objects.get(authUser__username=username)
    return user


@login_required
def newPost(request):
    username = request.user.username
    form = NewPostForm()
    user = Account.objects.get(authUser__username=username)
    if user.accessLevel in ['admin', 'author']:
        if request.method == "POST":
            if form.is_valid():
                form.author = Account.objects.get(authUser__username=username)
                form.save()


@login_required
def addNewPost(request):
    username = request.user.username
    user = Account.objects.get(authUser__username=request.user.username)
    if user.accessLevel == "admin":

        if request.method == "POST":
            form = NewPostForm(request.POST, request.FILES)

            if form.is_valid():
                print(request.FILES.dict())
                post = form.save(commit=False)
                post.author = Account.objects.get(authUser__username=username)
                # post.previewImage = request.FILES.dict()
                post.save()
                return HttpResponse("hey there")

            else:
                print(form.errors)
                return HttpResponse("failed")

        else:
            form = NewPostForm()

        return render(request, 'blog/post-editor.html', {"form": form, "user": user})

    return HttpResponse("access denied")


@login_required
def blogAdmin(request):
    username = request.user.username
    user = Account.objects.get(authUser__username=username)
    return render(request, 'blog/home.html', {"user": user})


def magsPage(request):
    user = getAuthStaffUser(request)
    journals = Journal.objects.all().order_by('releaseDate')
    context = {
        'journals_list': journals
    }
    return render(request, 'blog/magazine.html', context)

def aboutUs(request):
    pass
def showPost(request, url_slug):
    post = get_object_or_404(Post, slug=url_slug)
    categories = Category.objects.all()

    context = {
        "post": post,
        "categories": categories,
        "current_page_index": 1,

    }

    return render(request, 'blog/blog-page.html', context)


def postsRender(request, index=1):
    user = None
    if request.user.is_authenticated and not request.user.is_staff:
        username = request.user.username
        user = Account.objects.get(authUser__username=username)

    eachPagePosts = 6
    startPos = (index - 1) * eachPagePosts
    postsNum = Post.objects.count()
    pagesNum = math.ceil(postsNum / eachPagePosts)
    posts = Post.objects.all()
    featured = []

    for p in posts.iterator():
        if p.featured:
            featured.append(p)
    categories = Category.objects.all()
    latestEvent = Post.objects.filter(type='event').first()

    pageData = {
        "page_number": pagesNum,
        "current_page": index,
    }
    context = {
        "user": user,
        "posts_list": posts[startPos: startPos + eachPagePosts],
        "posts_featured": featured,
        "latest_event": latestEvent,
        "categories": categories,
        "pages_number": pagesNum,
        "current_page_index": index,
        "next_page_index": index + 1,
        "previous_page_index": index - 1,
        "current_category_selected": None
    }

    return render(request, 'blog/blog.html', context)


def postsByCategory(request, index=1, cat_slug=None):
    user = getAuthStaffUser(request)
    eachPagePosts = 6
    startPos = (index - 1) * eachPagePosts
    postsNum = Post.objects.count()
    pagesNum = math.ceil(postsNum / eachPagePosts)
    posts = Post.objects.all()
    featured = []

    for p in posts.iterator():
        if p.featured:
            featured.append(p)
    categories = Category.objects.all()

    latestEvent = Post.objects.filter(type='event').first()

    if cat_slug != None:
        posts_list = posts.filter(category__slug=cat_slug)[startPos: startPos + eachPagePosts]
    else:
        posts_list = posts[startPos: startPos + eachPagePosts]


    context = {
        "user": user,
        "posts_list": posts_list,
        "posts_featured": featured,
        "latest_event": latestEvent,
        "categories": categories,
        "pages_number": pagesNum,
        "current_page_index": index,
        "next_page_index": index+1,
        "previous_page_index": index-1,
        "current_category_selected": cat_slug
    }

    return render(request, 'blog/blog.html', context)


def mainPage(request, cat_slug=None):
    postsByCategory(request, index=1, cat_slug=cat_slug)


def downloadJournalFile(request, journal_id):
    pass


def getNextBlogPage(request, current_index, cat_slug=None):
    if cat_slug != None:
        postsRender(request, current_index + 1)
    else:
        postsByCategory(request, current_index + 1, cat_slug)


def getPreviousBlogPage(request, current_index, cat_slug=None):
    if current_index - 1 > 0:
        if cat_slug != None:
            postsRender(request, current_index - 1)
        else:
            postsByCategory(request, current_index - 1, cat_slug)

blog/templates/blog/home-test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body {
            margin: 0;
            padding: 0;
        }
        .sect {
            background: url("../../../static/dev-images/PMphotoshop.png");
            width: 100vh;
            height: 100vh;
            position: relative;
            -webkit-background-size: cover;
            background-size: cover;
        }
        .sect::before {

            content: '';
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            background: url("../../../static/dev-images/PMphotoshop.png");
            mix-blend-mode: hard-light;
            -webkit-background-size: cover;
            background-size: cover;


        }
        .sect::before {
            -webkit-animation: aimate .2s linear infinite;
            -o-animation: aimate .2s linear infinite;
            animation: aimate .2s linear infinite;
        }
        @keyframes aimate {
            0%{
                background-position: 5px 0;

            }

            20%{
                background-position: -5px 0;

            }
            30%{
            background-position: 5px 0;

            }
            40%{
                background-position: 5px 0;

            }
            50%{
                background-position: 5px 0;

            }

            60%{
                background-position: 50px 0;

            }
            70%{
                background-position: 9px 0px;

            }

            90%{
                background-position: -5px 10px;

            }
            91%{
                background-position: 0px 50px;

            }
            100%{
                background-position: 5px 0px;
                -ms-filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
                filter: hue-rotate(365deg);


            }

        }
    </style>
</head>
<body>
    <div id="glitch" class="sect">

    </div>
</body>
</html>

blog/templates/blog/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1> hello this is blog home page</h1>
    {% if user.authUser.is_authenticated %}
        <h1>we know you're {{ user.authUser.username.upper }}</h1>
        <a href="{% url 'blog:new-post' %}">publish your post here</a>
    {% endif %}
    <a href="http://localhost:8000/admin">go for admin</a>
    {% for post in posts_list %}
        <div class="post-container">
            <div id="{% if post.type == "event" %}event{% else %}post{% endif %}">
                <ul>
                    <li>title: {{ post.title }}</li>
                    <li>publish date: {{ post.publishDate }}</li>
                    <a href="{% url 'blog:post-view' post.slug %}">see whole here</a>
                </ul>
            </div>
        </div>
    {% endfor %}
</body>
</html>

blog/templates/blog/journals-archive.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>

<section id="intro">

</section>
<section id="mags" class="container card-deck">

</section>
<script type="javascript" src="{% static 'js/jquery.min.js' %}"></script>
</body>
</html>

blog/templates/blog/magazine.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Ring</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link href="../../../static/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Roboto|Titan+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Baloo+Tammudu" rel="stylesheet">  <link href="../../../static/css/owl.carousel.css" rel="stylesheet">
    <link href="{% static 'css/blog-css.css' %}" rel="stylesheet">

    <!-- Plugin CSS -->
    <link href="../../../static/css/magnific-popup.css" rel="stylesheet">
    <link href="../../../static/css/animate.min.css" rel="stylesheet">

    <link href="../../../static/css/magazine.css" rel="stylesheet">

</head>

<body id="page-top">
     <!-- Navigation -->
<nav class="extended-nav navbar navbar-expand-lg nav-pills navbar-light bg-light fixed-top px-2" style="position: fixed" id="main-nav">
        <div class="d-inline">
                <div id="logo" class=" pull-left">
                    <img class=" nav-logo pull-left" id="navbar-logo-s" src="../../../static/dev-images/logo.PNG" >
                </div>
                <div id="nav-display" class="fixed-top mt-4 text-left nav-display">
                    <h5 id="dis1" class="" >Computer Engineering Scientific association</h5>
                    <h5 id="dis2"  class="" >University of Tehran</h5>
                    <h5 id="dis3" class="d-block">Collage of Farabi</h5>
                </div>
        </div>
        <div  id="nav-display-shrinked" class="mt-4 text-left nav-display" style="display: none; position: absolute; left:6rem; top: -9px; ">
            <h1 style="font-size: 2rem">CESA</h1>
            <h5> university of tehran, campus of farabi</h5>

        </div>
        <div class="nav-responsive-collapse " style="z-index: 1000">

            <div class=" " id="navbarLinks">
                <ul class="navbar-nav ml-auto pull-right font-english">
                    <li class="nav-item ">
                        <a class="nav-link js-scroll-trigger" href="{% url 'about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'rings:mainPage' %}">Rings</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'blog:events' %}">Events</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'journals' %}">Journal</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'blog:blog' %}">Blog</a>
                    </li>
                </ul>
            </div>
        </div>
</nav>

<nav class="mb-0 usual-nav font-english navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand font-english-title" href="#">UTCF CESA</a>
  <button class="navbar-toggler pull-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
                    <li class="nav-item ">
                        <a class="nav-link js-scroll-trigger" href="{% url 'about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'rings:mainPage' %}">Rings</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'blog:events' %}">Events</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'journals' %}">Journal</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'blog:blog' %}">Blog</a>
                    </li>
    </ul>
  </div>
</nav>

      <div class="container" style="margin-top: 100px;">
          <div style="">
                 <h2>Magazine Archive</h2>
             </div>
            <div class="mb-5 row card-deck">
                {% for journal in journals_list %}
                    <div class="col-md-3">

                        <!-- Card -->
              <article class="card animated fadeInLeft">
                <img class="card-img-top img-responsive" src="{{ journal.coverImage.url }}" alt="Deer in nature" />
                <div class="card-block">
                  <h6 class="text-muted mt-1">{{ journal.releaseDate }}</h6>
                  <a href="#"><button class="button  download">Download</button></a>
        </div>
      </article ><!-- .end Card -->

                </div>
                {% endfor %}

      </div>
      </div>
     <section id="footer">
         <footer>
        <div class="container">
          <div class="row">

            <div  id="" class="  col-md-6" style="color: white">
                <h4 class="" style="margin-top: 4%; margin-bottom: 4%"><strong>SITE MAP</strong></h4>
                <div class="d-flex">
                    <ul class="site-map" style="">
                    <li> <a href="{% url 'blog:posts-by-category-notIndexed' cat_slug='classes' %}" class="">classes</a></li>
                     <li> <a href="{% url 'journals'%}" class="">journal archive</a></li>
                    <li> <a href="{% url 'blog:posts-by-category-notIndexed' cat_slug='up-and-runnings' %}" class="">up and runnings</a></li>
                    <li> <a href="{% url 'blog:blog' %}" class="">blog</a></li>
                </ul>
                 <ul class= "site-map" style="">
                    <li> <a href="{% url 'blog:posts-by-category-notIndexed' cat_slug='talks' %}" class="">Talks</a></li>
                     <li> <a href="{% url 'rings:ring-profiles' %}" class="">farabi rings</a></li>
                     <li> <a href="{% url 'blog:posts-by-category-notIndexed' cat_slug='code-battles' %}" class="">code battles contest</a></li>
                </ul>
                </div>




            </div>
              <div class="col-md-6" style="color: white">
              <h4 style="margin-top: 4%; margin-bottom: 8%">About Farabi CESA</h4>
              <p style="padding-bottom: 16%">CESA stands for Computer Engineering Scientific Association <br>
                            Farabi is a campus of university of Tehran which located in province of Qom.<br>
                            for more information about events held by us visit our blog

                            </p>
            </div>

          </div>
        </div>
      </footer>

    </section>

<!-- Bootstrap core JavaScript -->
<script src="../../../static/js/jquery.min.js"></script>
<script src="../../../static/js/sticky.js"></script>
<script src="../../../static/js/jquery.easing.min.js"></script>
<script src=../../../static/js/scrollreveal.min.js"></script>
<script>
        $(document).on("scroll", function () {
        const navShrinked = $("#nav-display-shrinked");
        const navNorm = $('#nav-display');
        const navLogo = $("#navbar-logo-s");

        if ($(document).scrollTop() > 60) {
            navNorm.addClass("nav-display-shrinking");
            navLogo.addClass("nav-logo-shrink");
            $("#main-nav").css('position', 'fixed');
        } else if ($(document).scrollTop() === 0) {
            navNorm.removeClass("nav-display-shrinking");
        } else if ($(document).scrollTop() < 60) {
            navLogo.removeClass("nav-logo-shrink").delay(1000).triggerHandler("focus")
        }
    });
</script>
</body>

</html>

blog/templates/blog/post-editor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>add post</title>
</head>
<body>
<h1> hello {{ user.username }}</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type = submit value="post">
</form>
</body>
</html>

blog/templates/blog/post-view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ post.tilte }}</title>
</head>
<body>
    <h1>{{ post.title }}</h1>
    <img src={{ post.previewImage.url }}>
    <p>{{ post.text|linebreaksbr }}</p>
</body>
</html>